package match

import (
	"math"
	"slices"
)

// The decay estimator: an exponential standing on a stationary noise floor,
// fitted where measureDecays used to draw a straight line through a truncated
// trace. Split out of features.go, which is the file that finds the partials
// this one then measures.
//
// measureDecays itself moved here in the same spirit when PLAN N17's window
// work pushed features.go past its length limit: what the two files divide is
// finding a partial from measuring how long it rings, and the bounds on what
// counts as a measurable ring time belong on this side of that line.

// decayTraceRateHz is the rate the decay trace is decimated to before the
// exponential-plus-floor refinement. The heterodyne low-passes the envelope at
// `cutoff`, bounded above at 40 Hz in measureDecays, so this is a factor of
// twenty-five clear of that envelope's own bandwidth and the decimation is
// information-preserving rather than a speed/accuracy trade.
const decayTraceRateHz = 2000

// powerDecibels converts a non-negative power to decibels.
//
// The three places this package turns a power into decibels — the truncated
// trace, the decimated trace, and the modelled level inside the decay fit's
// innermost loop — go through here so that what backs the conversion is one
// decision made once rather than three.
//
// It is math.Log, and that is a measured choice rather than a default. This is
// the hottest transcendental in the objective (17 % of Extract's profile), the
// package has no golden-file exposure to protect — the CI reference fixture is
// generated by internal/physical/analysis, which never calls match — and the
// adoption gates every term here is divided by are stated in tenths of a
// decibel, so an approximation accurate to 1.24e-5 in the natural logarithm
// (5.4e-5 dB of power) would have been admissible on accuracy grounds with three
// orders to spare.
//
// It is not admissible on speed grounds, which is the only reason it would have
// been wanted, and it was measured twice because the first measurement was
// against a defect.
//
// The first substitution cost 5.5 % more instructions in BenchmarkExtract. The
// cause turned out to be in algo-approx rather than here: its arithmetic lived
// in a generic body, compiled per gcshape and reached through a dictionary, so
// it would not inline across a module boundary — it won its own in-package
// benchmark and lost every consumer's. That has since been fixed there by
// splitting each algorithm into a non-generic float64 kernel behind an
// inlinable shim, after which FastLog measures 1.3x faster than math.Log from a
// separate module.
//
// It still loses here. Re-measured against the fixed library, pinned to one
// P-core and reproducible to four significant figures over three interleaved
// runs, BenchmarkExtract retires 77.45 G instructions with math.Log and 80.20 G
// with approx.FastLog64 — 3.6 % *more* — for cycle counts that are
// indistinguishable inside the run-to-run spread. Go's math.Log on amd64 is
// archLog, hand-written assembly; a Go series does not beat it on this shape of
// work whatever the call overhead.
//
// So: not a placeholder awaiting a faster log. The faster log was tried, the one
// real defect behind the first result was found and fixed upstream, and it was
// tried again.
func powerDecibels(power float64) float64 {
	return decibelsPerPower * math.Log(power)
}

// decayFit is one partial's decay read as an exponential standing on a floor.
type decayFit struct {
	slopeDBPerSecond float64
	interceptDB      float64
	rSquared         float64
	// rangeDB is 10*log10(P0/N): how far the exponential falls before the floor
	// overtakes it, and so how much evidence the slope was read from.
	rangeDB float64
}

// decayFloorFit is the estimator of Karjalainen, Antsalo, Mäkivirta, Peltonen &
// Välimäki, "Estimation of Modal Decay Parameters from Noisy Response
// Measurements" (JAES 50(11):867-878, 2002), which exists to replace exactly the
// log-linear-with-truncation fit that seeds it.
//
// The defect it repairs is structural rather than statistical. A measured
// partial is not an exponential; it is an exponential *plus a floor* — the
// recording's noise, the room, the skirts of every other partial that leaked
// past the heterodyne. A straight line fitted to the decibels of that sum is
// biased towards the floor's slope, which is zero, so every ring time comes back
// long. The usual defence is to truncate before the floor arrives, which is what
// DecayFitFloorDB does, and it trades the bias for two new problems: the
// truncation point depends on the very decay being measured, and a fast partial
// is left with almost no trace to fit.
//
// Modelling the floor removes the need for either. The fit is over the whole
// window, floor included:
//
//	p(t) = P0*exp(-a*t) + N,  fitted to 10*log10 of the measured power
//
// in decibels because that is the domain the error is uniform in and the domain
// the term it feeds is stated in. Three parameters, held as logarithms so they
// cannot go negative, solved by Levenberg-Marquardt from the log-linear
// estimate. Deterministic: fixed iteration count, fixed damping schedule, no
// randomness, so a rendered candidate scores identically on every run.
//
// It reports failure rather than a fallback value. The caller keeps the
// log-linear reading when the refinement does not converge on a decaying
// exponential, which is the conservative direction — the seed is what this
// repository measured everything with until now.
func decayFloorFit(times, trace []float64, seedSlope, seedIntercept float64) (decayFit, bool) {
	const (
		maxIterations = 60
		minPoints     = 16
		// Convergence: an improvement smaller than this in the mean squared dB
		// residual is smaller than anything the term downstream can resolve.
		tolerance = 1e-9
	)

	if len(times) < minPoints || seedSlope >= 0 {
		return decayFit{}, false
	}

	// The power decays as exp(-a*t) where the seed's slope is in dB of power
	// per second, so a = -slope * ln(10)/10.
	logPower := seedIntercept / decibelsPerPower
	logRate := math.Log(-seedSlope / decibelsPerPower)

	// The floor seed is the quietest thing in the trace, backed off by a decade
	// so the first step is taken from below it rather than through it.
	quietest := trace[0]
	for _, level := range trace {
		quietest = min(quietest, level)
	}

	logFloor := quietest/decibelsPerPower - math.Ln10

	// Loop-invariant for the whole fit: the times do not change between sweeps,
	// so whether they form an arithmetic progression is decided once here rather
	// than in each of the up-to-540 sweeps below. See decaySignalStep.
	stride, uniform := decaySignalStep(times)

	residual := decayFloorResidual(times, trace, stride, uniform, logPower, logRate, logFloor)
	damping := 1e-3

	for range maxIterations {
		// Normal equations for the three-parameter Gauss-Newton step, damped.
		var (
			normal [3][3]float64
			right  [3]float64
		)

		rate, floor := math.Exp(logRate), math.Exp(logFloor)

		levels := trace[:len(times)]

		// Same recurrence as decayFloorResidual, and the same fallback: signal is
		// stepped by a constant ratio when the times are uniform, and computed
		// point by point when they are not.
		signal, ratio := 0.0, 0.0
		if uniform {
			signal = math.Exp(logPower - rate*times[0])
			ratio = math.Exp(-rate * stride)
		}

		for i, elapsed := range times {
			if !uniform {
				signal = math.Exp(logPower - rate*elapsed)
			}

			modelled, gradient := decayFloorTerms(signal, floor, rate, elapsed)
			delta := levels[i] - modelled

			signal *= ratio

			for row := range 3 {
				right[row] += gradient[row] * delta

				for column := range 3 {
					normal[row][column] += gradient[row] * gradient[column]
				}
			}
		}

		improved := false

		for range 8 {
			damped := normal
			for row := range 3 {
				damped[row][row] *= 1 + damping
			}

			step, ok := solve3(damped, right)
			if !ok {
				break
			}

			trialPower := logPower + step[0]
			trialRate := logRate + step[1]
			trialFloor := logFloor + step[2]

			trial := decayFloorResidual(times, trace, stride, uniform,
				trialPower, trialRate, trialFloor)
			if trial < residual {
				logPower, logRate, logFloor = trialPower, trialRate, trialFloor
				improved = residual-trial > tolerance*max(1, residual)
				residual = trial
				damping = max(damping/10, 1e-12)

				break
			}

			damping *= 10
		}

		if !improved {
			break
		}
	}

	rate := math.Exp(logRate)
	if !(rate > 0) || math.IsNaN(residual) || math.IsInf(residual, 0) {
		return decayFit{}, false
	}

	// The floor is only identifiable if the trace actually reaches it. A partial
	// still standing above the recording's noise at the end of the window
	// constrains N from above and not at all from below, so the fit drives it to
	// zero and 10*log10(P0/N) runs away — 2e4 dB and worse were observed on the
	// licensed reference before this bound.
	//
	// Reporting the runaway would be reporting a confidence of infinity for a
	// perfectly ordinary partial. What the trace can support is the span it
	// covers, so the range is capped there: no partial is credited with more
	// evidence than its own envelope shows.
	quietestFitted := trace[0]
	loudest := trace[0]

	for _, level := range trace {
		quietestFitted = min(quietestFitted, level)
		loudest = max(loudest, level)
	}

	var variance float64

	mean := 0.0
	for _, level := range trace {
		mean += level
	}

	mean /= float64(len(trace))

	for _, level := range trace {
		variance += (level - mean) * (level - mean)
	}

	quality := 0.0
	if variance > 0 {
		quality = max(0, 1-residual*float64(len(trace))/variance)
	}

	return decayFit{
		slopeDBPerSecond: -rate * decibelsPerPower,
		interceptDB:      logPower * decibelsPerPower,
		rSquared:         quality,
		rangeDB:          min((logPower-logFloor)*decibelsPerPower, loudest-quietestFitted),
	}, true
}

// decayFloorTerms is the fitted level in dB at one time, and its gradient with
// respect to the three log-parameters, given that time's signal power
// P0*exp(-a*t) already evaluated.
//
// It takes rate = exp(logRate) and floor = exp(logFloor) rather than the
// logarithms, because both are constant for a whole Levenberg-Marquardt sweep
// and this is the innermost point of the fit: called once per trace point per
// gradient evaluation and once more per residual evaluation, of which there are
// up to nine per iteration and sixty iterations per partial. Computing them here
// meant three transcendentals per point where the fit needs one.
//
// It takes the signal rather than computing it for the same reason one level up:
// see decaySignalStep, which supplies it by recurrence when it can.
func decayFloorTerms(signal, floor, rate, elapsed float64) (level float64, gradient [3]float64) {
	total := signal + floor
	if total <= 0 {
		return math.Inf(-1), gradient
	}

	// One reciprocal rather than two divisions by the same denominator.
	reciprocal := 1 / total
	signalShare := signal * reciprocal

	// d/dlogRate carries the extra factor of rate*t from the chain rule, and its
	// sign is what makes the rate identifiable at all: only the part of the
	// trace where the signal still stands above the floor constrains it.
	gradient[0] = decibelsPerPower * signalShare
	gradient[1] = -decibelsPerPower * signalShare * rate * elapsed
	gradient[2] = decibelsPerPower * floor * reciprocal

	return powerDecibels(total), gradient
}

// decaySignalStep is the ratio between one trace point's signal power and the
// next one's, when the trace times are an arithmetic progression.
//
// This is the fit's one remaining transcendental made loop-invariant. The model
// term is exp(logPower - a*t_i), and the times measureDecays builds are
// float64(sample)*secondsPerSample with a fixed sample stride, so t_i = t_0 +
// i*dt and the sequence is geometric: signal_{i+1} = signal_i * exp(-a*dt). One
// math.Exp per sweep replaces one per point, and a sweep is 1,600-3,100 points.
//
// The progression is *checked*, not assumed. The loop that builds fullTimes
// skips any sample whose squared envelope is not positive, so the times can have
// gaps, and a gap would silently make the recurrence model a different drum. A
// missing point doubles a difference, so the tolerance below (a relative 2^-20,
// ten orders of magnitude above the ulp-scale wobble of an exact progression
// rounded to float64) separates the two cases with room to spare while costing
// one subtract and compare per point, once per fit rather than once per sweep.
//
// The second return is false when the times are not uniform, and the caller then
// keeps the per-point math.Exp. It is also false for a degenerate or descending
// stride, which cannot occur here but would make the recurrence meaningless.
//
// On the accumulated drift: a sweep multiplies by a constant ratio in (0,1) at
// most ~3,100 times, and the rounding of each product is at most half an ulp, so
// the relative error grows as at most 3100*2^-53 ~ 3.4e-13.
// TestDecaySignalRecurrenceDrift measures it on the real traces and finds
// 1.94e-13 — the bound met rather than beaten, and still four orders inside the
// fit's own 1e-9 convergence tolerance, so nothing it does can move a ring time.
func decaySignalStep(times []float64) (stride float64, uniform bool) {
	if len(times) < 2 {
		return 0, false
	}

	stride = times[1] - times[0]
	if !(stride > 0) {
		return 0, false
	}

	const relativeTolerance = 1.0 / (1 << 20)

	tolerance := stride * relativeTolerance

	for i := 1; i < len(times)-1; i++ {
		if math.Abs(times[i+1]-times[i]-stride) > tolerance {
			return 0, false
		}
	}

	return stride, true
}

// decayFloorResidual is the mean squared dB error of one parameter set.
//
// stride and uniform come from decaySignalStep over the same times slice; the
// caller computes them once per fit rather than once per sweep.
func decayFloorResidual(times, trace []float64, stride float64, uniform bool,
	logPower, logRate, logFloor float64,
) float64 {
	rate, floor := math.Exp(logRate), math.Exp(logFloor)
	levels := trace[:len(times)]

	sum := 0.0

	if uniform {
		signal := math.Exp(logPower - rate*times[0])
		ratio := math.Exp(-rate * stride)

		for i, elapsed := range times {
			modelled, _ := decayFloorTerms(signal, floor, rate, elapsed)
			if math.IsInf(modelled, 0) {
				return math.Inf(1)
			}

			delta := levels[i] - modelled
			sum += delta * delta

			signal *= ratio
		}

		return sum / float64(len(times))
	}

	for i, elapsed := range times {
		modelled, _ := decayFloorTerms(math.Exp(logPower-rate*elapsed), floor, rate, elapsed)
		if math.IsInf(modelled, 0) {
			return math.Inf(1)
		}

		delta := levels[i] - modelled
		sum += delta * delta
	}

	return sum / float64(len(times))
}

// solve3 solves a 3x3 system by Gaussian elimination with partial pivoting. The
// matrix is a damped Gramian, so it is symmetric positive semi-definite and a
// Cholesky would do; pivoting is used anyway because the damping is what keeps
// it definite and the caller must be told when that has stopped being true.
func solve3(matrix [3][3]float64, right [3]float64) ([3]float64, bool) {
	var solution [3]float64

	for column := range 3 {
		pivot := column
		for row := column + 1; row < 3; row++ {
			if math.Abs(matrix[row][column]) > math.Abs(matrix[pivot][column]) {
				pivot = row
			}
		}

		if matrix[pivot][column] == 0 {
			return solution, false
		}

		matrix[column], matrix[pivot] = matrix[pivot], matrix[column]
		right[column], right[pivot] = right[pivot], right[column]

		for row := column + 1; row < 3; row++ {
			factor := matrix[row][column] / matrix[column][column]
			for inner := column; inner < 3; inner++ {
				matrix[row][inner] -= factor * matrix[column][inner]
			}

			right[row] -= factor * right[column]
		}
	}

	for column := 2; column >= 0; column-- {
		sum := right[column]
		for inner := column + 1; inner < 3; inner++ {
			sum -= matrix[column][inner] * solution[inner]
		}

		solution[column] = sum / matrix[column][column]
	}

	if math.IsNaN(solution[0]) || math.IsNaN(solution[1]) || math.IsNaN(solution[2]) {
		return solution, false
	}

	return solution, true
}

// t60From converts a log-magnitude slope in dB per second into a ring time.
func t60From(slopeDBPerSecond float64) float64 {
	return -60 / slopeDBPerSecond
}

// fastestObservableT60 is the shortest ring time anything the envelope filter
// can output, and so the fastest decay a fit through it can be measuring.
//
// The filter heterodyne builds is a fourth-order Butterworth. Its two pole
// pairs decay at zeta*omega_n with zeta = 1/(2Q), and the faster of them —
// Q = 0.5411961 — sets the bound below: no input whatsoever produces an output
// that falls 60 dB faster than that. A fit reporting one is not measuring a
// short partial, it is reading a fragment of something else, and the level
// implied by extrapolating that slope back to the strike is catastrophic rather
// than merely wrong. That is what this bound is enforced against.
//
// It is deliberately the *faster* pole and not the slower one. The slower pair
// rings for 2.4 times as long — 287 ms at the 10 Hz cutoff floor, longer than
// several of this reference's partials — and it is tempting to argue that a
// partial decaying faster than that cannot be observed either, because the
// filtered tail would be the filter's own transient rather than the partial's.
// That argument is wrong, and it was tested rather than reasoned about:
// TestCloseNeighboursDoNotBiasEitherRingTime puts two partials 18 Hz apart
// ringing for 280 ms through exactly that 10 Hz filter and recovers both to
// within three per cent. The fit is dominated by the signal term, which stands
// far above the filter transient until the -45 dB truncation has already ended
// the fit. Enforcing the slower bound would have discarded this drum's own
// fundamental for no reason at all.
func fastestObservableT60(cutoffHz float64) float64 {
	const (
		dampingRatio = 1 / (2 * 0.5411961)
		numerator    = 3 * math.Ln10 / (dampingRatio * 2 * math.Pi)
	)

	return numerator / cutoffHz
}

// minimumRefinementSpanSeconds is the shortest window the exponential-plus-floor
// refinement may be fitted over, however short the partial is.
//
// The refinement's floor is a *parameter*, not something to truncate away, and a
// parameter has to be identifiable from the data. Two spans of a fast partial are
// not enough data: at 2 kHz decimation a 26 ms partial gets 105 points, half of
// them signal, and the three-parameter fit is then free to trade a steep slope
// against a low floor at almost no cost in residual. The result is not a wrong
// ring time, which would be survivable; it is a wrong *level*, because the level
// is that fitted line extrapolated back to the strike.
//
// This was measured, and it was measured as damage already done. PLAN N17 added
// the per-partial bound above with no lower limit, and on
// reference/tt08x08/lp/hd/v16 the right channel's 2511.8 Hz component was then
// fitted over 105 points at R^2 0.508, came back at T60 45 ms, and extrapolated
// to an intercept of +31.4 dB against its own observed peak of -41.2 dB. It
// became the loudest thing in the table, every real partial fell below
// PartialFloorDB relative to it, and a sixteen-partial table became two — both
// above 2 kHz, on a drum whose fundamental is 240 Hz. This is the same failure
// fastestObservableT60 was written for, arriving through a different door.
//
// It is not a rare accident. Across the sixteen takes, both channels named the
// ~240 Hz fundamental as their loudest partial on 15 of 16 before N17 and on only
// 7 of 16 after it. Since the level table is normalised to whatever is loudest
// and measureGlide picks its partial off that, one bad fit re-bases everything
// downstream — which is how a bound meant to sharpen ring times moved the glide
// term's reproducibility floor from 2.3 cents to 286.
//
// 0.8 s is where that stops, chosen by re-measuring the objective's own floor
// over the sixteen takes at a sweep of lower limits (p90, cmd/measure-objective):
//
//	limit        none   0.4 s   0.8 s   1.0 s   1.2 s   1.55 s  (pre-N17)
//	glide       286.0    86.2    23.4    23.4   119.8   119.8     2.3
//	decay       0.745   0.654   0.535   0.548   0.506   0.512    0.589
//	frequency    82.6    72.8    65.5    69.4    64.2    57.2     65.0
//	level       11.23    7.41    6.42    6.33    5.92    5.71     6.76
//	unmatched   0.434   0.348   0.223   0.245   0.204   0.215    0.280
//	spurious    0.362   0.360   0.239   0.261   0.204   0.228    0.293
//
// At 0.8 s every term is at or better than it was before N17 except glide, and
// glide is an order of magnitude better than the unbounded version. Past 0.8 s
// the partial terms keep improving slowly and glide falls apart again, because at
// 1.55 s the bound is inert (the window is 1.55 s long) and the fits it was
// protecting come back. 0.8 s is the corner, not a compromise between two goods.
//
// The reason this is a *lower limit* rather than a reason to delete the bound: a
// reproducibility measurement compares two microphones on one hit, so it cannot
// see a bias both channels share, and the neighbour contamination the bound
// exists for is exactly such a bias. Reproducibility can only say the bound was
// costing more than it could possibly be worth. Held above 0.8 s it is no longer
// doing so, and it still shortens the window for every partial whose own span is
// under 0.4 s, which is the case it was written for.
const minimumRefinementSpanSeconds = 0.8

// minimumEvaluationFallDB is how far a partial must actually fall inside its fit
// window before a ring time may be extrapolated from it.
//
// 20 dB is ISO 3382's own answer. A T60 is a 60 dB fall, and a 60 dB fall is
// almost never observed above the noise, so the standard defines T20 and T30 —
// ring times read off a 20 or 30 dB decay and multiplied out. It sanctions
// nothing shorter than 20 dB, and this is the same judgement applied to a
// partial rather than to a room: below it the extrapolation factor passes three
// and the answer is mostly the estimator's opinion.
const minimumEvaluationFallDB = 20

// slowestSupportedT60 is the longest ring time a fit window of this length can
// carry evidence for, which by the constant above is exactly three times the
// window.
//
// This is the counterpart of fastestObservableT60 and catches the opposite
// failure. That bound rejects a decay too fast for the envelope filter to have
// produced; this one rejects a decay too slow for the window to have seen. The
// two are not symmetric in how they go wrong: an impossibly fast fit announces
// itself with a catastrophic intercept, while an unsupported slow one looks
// entirely ordinary and is simply the fitted line's opinion about audio that was
// never examined.
//
// The failure is not hypothetical. On reference/tt08x08/lp/hd, measured through
// the 0.60 s window this repository shipped until PLAN N17, the ~358 Hz partial
// came back between 5.1 and 10.4 s across the sixteen takes at R² 0.12-0.77 —
// a factor of two of disagreement about one component of one drum. It is a real
// partial: at a 1.60 s window the same component reads 2.48-2.59 s at R²
// 0.95-0.98, a factor of 1.04. Nothing about the drum changed, only whether the
// window contained the decay being reported.
//
// Note what this deliberately does not do. It does not bound a ring time against
// the file's own length, which was the first criterion tried and is wrong: a
// 2.5 s partial in a 2.08 s recording is perfectly measurable if it fell 37 dB
// while the window was open, and twelve of this reference's partials are exactly
// that. Evidence is the fall, not the duration.
func slowestSupportedT60(fitSpanSeconds float64) float64 {
	return 60 * fitSpanSeconds / minimumEvaluationFallDB
}

// measureDecays fits each partial's own decay, and corrects its level for it.
//
// Two measurements, from two different views of the same partial, because
// neither view can do both jobs.
//
// The *rate* comes from the time domain: the signal is heterodyned to
// baseband and low-passed, and the log of the resulting envelope is fitted
// with a straight line.
//
// The *level* is that same fitted line's value at the strike — its intercept.
//
// It must not be the envelope's peak inside the fit window: resolving a pair
// 10 Hz apart needs a filter whose impulse response is longer than 150 ms, and
// the strike transient smeared through one of those put this reference's
// 212 Hz partial 32 dB too loud, above the fundamental. The intercept is not
// that reading. The fit starts at DecayFitStartSeconds, after the transient,
// and the intercept extrapolates the fitted decay back to the origin.
//
// Nor can it be the detection spectrum divided by the attenuation that
// spectrum's window applied to a partial decaying at the fitted rate. That
// divisor is exact for an isolated exponential and hopelessly ill-conditioned:
// across the ring times this reference actually contains it spans 16 dB to
// 100 dB, so the reported level was mostly a restatement of the fitted rate. A
// ten per cent error in T60 at 0.12 s moved the level by 4.5 dB, and a partial
// whose fit came back short was promoted past the fundamental — a 73 ms
// component was reported as the loudest thing in the recording, which pushed
// every genuine partial below the detection floor, because levels are relative
// to the strongest. TestShortPartialsDoNotOutrankLongOnes pins it.
func measureDecays(work *extractScratch, hit []float64, sampleRateHz float64, options Options, partials []Partial) []Partial {
	levelLinear := make([]float64, len(partials))

	inPhase, quadrature := work.basebandPair(len(hit))

	// Loop-invariant: the truncation floor is a fixed number of decibels below
	// each partial's own peak, so the ratio it multiplies by is the same for
	// every partial and is a math.Pow that used to run once per partial.
	floorRatio := math.Exp(options.DecayFitFloorDB * amplitudePerDecibel)
	floorRatioSquared := floorRatio * floorRatio

	secondsPerSample := 1 / sampleRateHz

	for index := range partials {
		// Half the distance to the nearest neighbour, bounded: too narrow and
		// the filter's own ring outlasts the partial, too wide and the
		// neighbour's decay is measured instead of this one's.
		cutoff := clampFloat(0.5*neighbourSpacing(partials, index), 10, 40)

		heterodyneInto(inPhase, quadrature, hit, sampleRateHz, partials[index].FrequencyHz, cutoff, 2)

		start := clampIndex(int(options.DecayFitStartSeconds*sampleRateHz), len(hit))

		end := clampIndex(int(options.DecayFitEndSeconds*sampleRateHz), len(hit))
		if end-start < 16 {
			continue
		}

		// Both loops below work in squared magnitude, so neither takes a square
		// root at all — this is not Hypot traded for a cheaper Sqrt.
		//
		// The peak survives because x -> sqrt(x) is increasing, so the largest
		// squared magnitude belongs to the largest magnitude; one root at the end
		// recovers it. The trace survives because 20*log10(sqrt(x)) is 10*log10(x)
		// identically, so the root the decibel conversion was undoing never needs
		// taking. The floor comparison is squared to match, which is exact for
		// non-negative operands.
		// The squared envelope is written down once and read twice, rather than
		// being recomputed by each of the three passes that want it. The
		// heterodyne output it comes from is scratch too, so this costs one more
		// reused buffer and saves two multiply-add sweeps of the fit window per
		// partial.
		envelope := growFloats(work.envelope, end-start)
		work.envelope = envelope

		peakSquared := 0.0

		realPart, imaginaryPart := inPhase[start:end], quadrature[start:end]
		envelope = envelope[:len(realPart)]

		for i, sample := range realPart {
			imaginary := imaginaryPart[i]
			squared := sample*sample + imaginary*imaginary
			envelope[i] = squared

			if squared > peakSquared {
				peakSquared = squared
			}
		}

		if peakSquared <= 0 {
			continue
		}

		times := growFloats(work.times, 0)
		trace := growFloats(work.trace, 0)

		// The floor is a ratio of the peak, so squaring it is exact for
		// non-negative operands and no square root is taken at all.
		floorSquared := peakSquared * floorRatioSquared

		for i, squared := range envelope {
			if squared < floorSquared {
				// Below the fit floor the trace is noise or a neighbour, and
				// including it would flatten every slope towards zero.
				break
			}

			times = append(times, float64(start+i)*secondsPerSample)
			trace = append(trace, powerDecibels(squared))
		}

		work.times, work.trace = times, trace

		if len(times) < 16 {
			continue
		}

		// The refinement below is fitted past the truncation, floor and all,
		// because in its model the floor is a parameter rather than something to
		// truncate away. But it is not fitted over the *whole* window, and the
		// bound is what keeps a long window from being worse than a short one.
		//
		// Its model is one exponential plus a **stationary** floor. That holds
		// for as long as the band contains this partial and the recording's
		// noise. It stops holding once the partial has gone: what is left in the
		// band is the skirt of whatever else is near it, and a neighbour that
		// rings longer is a second *decaying* exponential, which the model can
		// only account for by bending the first one towards it.
		//
		// The failure is not subtle. Two partials 27.7 Hz apart, the lower
		// ringing 0.21 s and the louder-lived upper one 0.64 s: fitted to a
		// 0.60 s window the lower reads T60 0.240 s at its true level, and
		// fitted to a 1.60 s window it reads 0.443 s at -21.5 dB, because two
		// thirds of that window is the neighbour. The level is the worse of the
		// two errors — it is the fitted line extrapolated back to the strike, so
		// a slope bent flat drags the intercept down with it.
		//
		// So the window is per partial and is stated in the partial's own terms:
		// the span over which it stood above its floor, doubled. One span of
		// decay to fit, one span of floor to identify the floor, and nothing
		// beyond that, where there is no more information about *this* partial
		// and a growing amount about its neighbours. It is still bounded by the
		// global window, which is what a short recording enforces.
		//
		// And it is bounded from *below* by minimumRefinementSpanSeconds, which
		// the first version of this was missing and which cost the objective more
		// than the bound itself was worth. See that constant.
		fitEnd := min(end, start+max(2*len(times),
			int(minimumRefinementSpanSeconds*sampleRateHz)))

		// It is decimated first: the envelope has already been low-passed at
		// `cutoff`, which is at most 40 Hz, so at decayTraceRateHz it is
		// oversampled several-fold and the fit runs over hundreds of points
		// rather than tens of thousands. That matters — a fit run scores
		// thousands of candidates, and an undecimated Levenberg-Marquardt here
		// would dominate the whole search.
		step := max(1, int(sampleRateHz/decayTraceRateHz))
		fullTimes := growFloats(work.fullTimes, 0)
		fullTrace := growFloats(work.fullTrace, 0)

		for sample := start; sample < fitEnd; sample += step {
			squared := envelope[sample-start]
			if squared <= 0 {
				continue
			}

			fullTimes = append(fullTimes, float64(sample)*secondsPerSample)
			fullTrace = append(fullTrace, powerDecibels(squared))
		}

		work.fullTimes, work.fullTrace = fullTimes, fullTrace

		slope, interceptDB, fitQuality := linearFit(times, trace)
		// Without the refinement the honest dynamic range is the span the
		// truncated trace actually covered, which the -45 dB floor bounds.
		rangeDB := trace[0] - trace[len(trace)-1]

		if refined, ok := decayFloorFit(fullTimes, fullTrace, slope, interceptDB); ok {
			slope, interceptDB = refined.slopeDBPerSecond, refined.interceptDB
			fitQuality, rangeDB = refined.rSquared, refined.rangeDB
		}

		if slope >= 0 {
			// No decay to speak of: the trace is noise, or a neighbour bleeding
			// through. Neither its level nor its ring time means anything, so
			// the partial is dropped rather than reported with one of them made
			// up.
			continue
		}

		if t60From(slope) < fastestObservableT60(cutoff) {
			// Faster than anything the filter the envelope was measured through
			// can output. See fastestObservableT60: such a fit is reading a
			// fragment of something else, and the intercept it implies is
			// catastrophic rather than merely wrong.
			//
			// On v10 of the licensed reference this one condition is the
			// difference between a table of one partial and a table of sixteen.
			// The 2349.6 Hz candidate there was fitted over 6.1 ms of trace at
			// -4034 dB/s and extrapolated back to an intercept of +137 dB —
			// 144 dB above the loudest real partial — after which every genuine
			// partial sat below the -42 dB relative floor and was discarded.
			// TestImpossibleDecaysDoNotSilenceTheTable pins it.
			continue
		}

		if t60From(slope) > slowestSupportedT60(float64(end-start)/sampleRateHz) {
			// Slower than this window can carry evidence for. See
			// slowestSupportedT60: the partial is dropped rather than reported
			// with a ring time the recording was never examined far enough to
			// support.
			//
			// The span is measured from the clamped sample indices rather than
			// from DecayFitEndSeconds, so a file that ends before the window
			// does is judged on the audio it actually has.
			continue
		}

		// The level is the fitted line's value at the strike, read off the
		// partial's own envelope. The previous form divided the sustain
		// transform's magnitude by that window's attenuation integral, which is
		// exact for an isolated exponential and hopelessly ill-conditioned: over
		// the T60 range this reference actually contains, that divisor spans
		// 16 dB to 100 dB, so the reported level was mostly a restatement of the
		// fitted decay rate. A ten per cent error in T60 at 0.12 s moved the
		// level by 4.5 dB, and a partial whose fit came back short could be
		// promoted past the fundamental — which is what happened, repeatedly,
		// and what made the detection guards load-bearing.
		//
		// The intercept is the same quantity — amplitude at t=0 — measured
		// directly. It extrapolates back only as far as DecayFitStartSeconds
		// rather than through the whole Hann taper, and it is a least-squares
		// fit over hundreds of samples rather than a ratio of two numbers.
		levelLinear[index] = math.Exp(interceptDB * amplitudePerDecibel)
		partials[index].T60Seconds = t60From(slope)
		partials[index].FitQuality = fitQuality
		partials[index].DecayRangeDB = rangeDB
	}

	strongest := 0.0
	for _, level := range levelLinear {
		strongest = max(strongest, level)
	}

	if strongest <= 0 {
		return nil
	}

	strongestReciprocal := 1 / strongest
	kept := partials[:0]

	for index := range partials {
		if levelLinear[index] <= 0 {
			continue
		}

		levelDB := decibelsPerAmplitude * math.Log(levelLinear[index]*strongestReciprocal)
		if levelDB < options.PartialFloorDB {
			continue
		}

		partials[index].LevelDB = levelDB
		kept = append(kept, partials[index])
	}

	if len(kept) > options.MaxPartials {
		// Sorted in place: kept is this function's own compaction of partials,
		// which the caller handed over, so there is nothing a copy would
		// protect. The final sort below restores frequency order.
		slices.SortFunc(kept, func(a, b Partial) int {
			switch {
			case a.LevelDB > b.LevelDB:
				return -1
			case a.LevelDB < b.LevelDB:
				return 1
			default:
				return 0
			}
		})

		kept = kept[:options.MaxPartials]
		slices.SortFunc(kept, func(a, b Partial) int {
			switch {
			case a.FrequencyHz < b.FrequencyHz:
				return -1
			case a.FrequencyHz > b.FrequencyHz:
				return 1
			default:
				return 0
			}
		})
	}

	return kept
}
