//go:build purego

package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"sort"
)

// Guards for an artefact written by an older or differently configured emitter,
// so a figure fails loudly rather than drawing an empty axis.
var (
	errNoBatterHead     = errors.New("model data has no batter head")
	errNoFundamental    = errors.New("model data has no (0,1) mode to normalise against")
	errNoCavityResponse = errors.New("model data has no cavity response")
)

// modelData is the part of cmd/analyze-physical's -paper-data artefact the model
// figures need.
//
// Everything in it is closed-form — the modal bank from the dispersion relation
// and the loss law, the cavity curves from the continuous-time reference solve —
// so unlike the fit report it depends on no render, no recording and no seed.
// That is what lets the model figures be regenerated by anyone with the
// repository.
type modelData struct {
	SchemaVersion int         `json:"schemaVersion"`
	Heads         []modelHead `json:"heads"`
	Modes         []modelMode `json:"modes"`
	Tiers         []modelTier `json:"tiers"`
	AttackBands   []modelBand `json:"attackBands"`

	CavityResponse struct {
		FrequencyHz []float64     `json:"frequencyHz"`
		Curves      []cavityCurve `json:"curves"`
	} `json:"cavityResponse"`
}

type modelHead struct {
	Name             string  `json:"name"`
	AxisymmetricOnly bool    `json:"axisymmetricOnly"`
	RadiusM          float64 `json:"radiusM"`
	WaveSpeedMPerS   float64 `json:"waveSpeedMPerS"`
	Loss0PerSecond   float64 `json:"loss0PerSecond"`
	Loss1MPerSecond  float64 `json:"loss1MPerSecond"`
	Loss2M2PerSecond float64 `json:"loss2M2PerSecond"`
	ModeCount        int     `json:"modeCount"`
}

// structuralDecayAt evaluates the head's own loss law at a frequency, through
// the wavenumber the model reaches it by. This is the same evaluation the attack
// layer makes to derive its band releases, which is why the loss figure can show
// the layer sitting on the law's continuation rather than beside it.
func (h modelHead) structuralDecayAt(frequencyHz float64) float64 {
	wavenumber := 2 * math.Pi * frequencyHz / h.WaveSpeedMPerS

	return h.Loss0PerSecond +
		h.Loss1MPerSecond*wavenumber +
		h.Loss2M2PerSecond*wavenumber*wavenumber
}

// dampingRatio is the fraction of critical damping the k¹ loss term alone
// implies: with omega = c*k, that term contributes d1*k to the decay rate and so
// d1/c to gamma/omega, independent of the mode. It is the law the calibration
// aims at, and the line the loss figure is read against.
func (h modelHead) dampingRatio() float64 {
	if h.WaveSpeedMPerS == 0 {
		return 0
	}

	return h.Loss1MPerSecond / h.WaveSpeedMPerS
}

// head returns one head's constitutive record by name.
func (d *modelData) head(name string) (modelHead, bool) {
	for _, candidate := range d.Heads {
		if candidate.Name == name {
			return candidate, true
		}
	}

	return modelHead{}, false
}

type modelMode struct {
	Head                     string  `json:"head"`
	AzimuthalOrder           int     `json:"azimuthalOrder"`
	RadialOrder              int     `json:"radialOrder"`
	FrequencyHz              float64 `json:"frequencyHz"`
	WavenumberPerM           float64 `json:"wavenumberPerM"`
	DampingRatio             float64 `json:"dampingRatio"`
	StructuralDecayPerSecond float64 `json:"structuralDecayPerSecond"`
	RadiationDecayPerSecond  float64 `json:"radiationDecayPerSecond"`
	DecayCorrectionPerSecond float64 `json:"decayCorrectionPerSecond"`
	DecayRatePerSecond       float64 `json:"decayRatePerSecond"`
	T60Seconds               float64 `json:"t60Seconds"`
	RadiationWeight          float64 `json:"radiationWeight"`
	FarFieldRadiationWeight  float64 `json:"farFieldRadiationWeight"`
}

type modelTier struct {
	Quality       string  `json:"quality"`
	SlotBudget    int     `json:"slotBudget"`
	BatterModes   int     `json:"batterModes"`
	ResonantModes int     `json:"resonantModes"`
	TopModeHz     float64 `json:"topModeHz"`
}

type modelBand struct {
	CentreHz   float64 `json:"centreHz"`
	T60Seconds float64 `json:"t60Seconds"`
}

type cavityCurve struct {
	StiffnessScale float64   `json:"stiffnessScale"`
	MagnitudeDB    []float64 `json:"magnitudeDb"`
	LowerBranchHz  float64   `json:"lowerBranchHz"`
	UpperBranchHz  float64   `json:"upperBranchHz"`
}

func loadModelData(path string) (*modelData, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var parsed modelData
	if err := json.Unmarshal(raw, &parsed); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}

	if len(parsed.Modes) == 0 {
		return nil, fmt.Errorf("%s carries no modes", path)
	}

	return &parsed, nil
}

// byFrequency returns the modes of one head, or of every head when name is
// empty, sorted by frequency. The artefact concatenates the two heads, so a
// figure that plotted it in file order would draw the resonant head's six modes
// as a line running backwards across the axis.
func (d *modelData) byFrequency(head string) []modelMode {
	selected := make([]modelMode, 0, len(d.Modes))

	for _, mode := range d.Modes {
		if head == "" || mode.Head == head {
			selected = append(selected, mode)
		}
	}

	sort.Slice(selected, func(i, j int) bool {
		return selected[i].FrequencyHz < selected[j].FrequencyHz
	})

	return selected
}

// fundamentalWeight is the radiation weight of the (0,1), the mode every other
// weight is quoted against. Its magnitude, because the weight's sign is a phase
// convention of the mode shape and carries no level information.
//
// Each microphone model is normalised against its own fundamental, so the two
// panels of the radiation figure compare partial *balance* rather than level.
// Level is not the comparison to make: the near-field term raises the whole sum
// and the output gain is fitted after it, so an absolute comparison would report
// a gain calibration rather than a radiation property.
func (d *modelData) fundamentalWeight(pick func(modelMode) float64) float64 {
	for _, mode := range d.Modes {
		if mode.AzimuthalOrder == 0 && mode.RadialOrder == 1 {
			return math.Abs(pick(mode))
		}
	}

	return 0
}
