// Command gen-voiceparams writes the TypeScript mirror of the engine's
// per-voice parameter table.
//
// The frontend needs the parameter list, its defaults and its ranges
// *synchronously* at mount: DrumMachine renders (and loadInitialState decodes a
// saved blob) while the WASM worker is still loading, so a runtime call into
// the engine is too late. Hand-maintaining a second copy of the table would
// silently drift from the numbers that are literally the sound, so the table is
// generated instead and the result is committed; CI regenerates and diffs.
//
// Run it with `just gen-params`, which also formats the output with prettier.
package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/cwbudde/algo-drum/internal/drum"
)

func main() {
	out := flag.String("o", "", "output file (default: stdout)")

	flag.Parse()

	source := generate()

	if *out == "" {
		fmt.Print(source)

		return
	}

	if err := os.WriteFile(*out, []byte(source), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-voiceparams: %v\n", err)
		os.Exit(1)
	}
}

// num formats a float so the TypeScript literal parses back to the exact same
// float64. 'g' with 17 significant digits round-trips every double.
func num(v float64) string {
	return strconv.FormatFloat(v, 'g', 17, 64)
}

func quote(s string) string {
	return strconv.Quote(s)
}

func generate() string {
	var out strings.Builder

	out.WriteString(`// Code generated by cmd/gen-voiceparams. DO NOT EDIT.
//
// Mirror of the per-voice synthesis parameter table in internal/drum/params.go.
// Regenerate with ` + "`just gen-params`" + ` after changing a spec there; CI fails
// if this file and the Go table disagree.

/** One tweakable synthesis parameter of one voice. */
export interface VoiceParamSpec {
  /** Stable persistence key. Append-only: the index is a byte slot in share links. */
  readonly id: string;
  /** Knob face, kept short. */
  readonly label: string;
  /** Accessible-name fragment, e.g. "body pitch". */
  readonly name: string;
  /** Engineering unit for the readout ("Hz", "s", or empty). */
  readonly unit: string;
  /** Labels for a discrete selector; absent for continuous parameters. */
  readonly choices?: readonly string[];
  /** Curve used to map the normalized position onto [min, max]. */
  readonly kind: "exp" | "lin";
  readonly min: number;
  readonly max: number;
  /** The constant the voice shipped with, in engineering units. */
  readonly shipped: number;
  /** Normalized position of the shipped value; where the knob rests and resets to. */
  readonly default: number;
  /** Digits after the decimal point in the readout. */
  readonly digits: number;
}

`)

	fmt.Fprintf(&out, "/** Widest voice's parameter count; also the per-voice persistence slot count. */\nexport const VOICE_PARAM_CAPACITY = %d;\n\n", maxParams())

	out.WriteString("/** Display names, in engine track order (0 = Bass Drum … 4 = Cymbal). */\nexport const VOICE_NAMES: readonly string[] = [\n")

	for track := range drum.TrackCount {
		fmt.Fprintf(&out, "  %s,\n", quote(drum.VoiceName(track)))
	}

	out.WriteString("];\n\n/** Parameter tables, in engine track order. */\nexport const VOICE_PARAMS: readonly (readonly VoiceParamSpec[])[] = [\n")

	for track := range drum.TrackCount {
		fmt.Fprintf(&out, "  // %s\n  [\n", drum.VoiceName(track))

		for _, spec := range drum.SpecsForTrack(track) {
			fmt.Fprintf(&out, "    {\n")
			fmt.Fprintf(&out, "      id: %s,\n", quote(spec.ID))
			fmt.Fprintf(&out, "      label: %s,\n", quote(spec.Label))
			fmt.Fprintf(&out, "      name: %s,\n", quote(spec.Name))
			fmt.Fprintf(&out, "      unit: %s,\n", quote(spec.Unit))
			fmt.Fprintf(&out, "      kind: %s,\n", quote(spec.Kind.String()))
			fmt.Fprintf(&out, "      min: %s,\n", num(spec.Min))
			fmt.Fprintf(&out, "      max: %s,\n", num(spec.Max))
			fmt.Fprintf(&out, "      shipped: %s,\n", num(spec.Shipped))
			fmt.Fprintf(&out, "      default: %s,\n", num(spec.Default))
			fmt.Fprintf(&out, "      digits: %d,\n", spec.Digits)
			fmt.Fprintf(&out, "    },\n")
		}

		out.WriteString("  ],\n")
	}

	out.WriteString("];\n")

	out.WriteString("\n/** Physical Tom parameter table, separate from the procedural Tom bank. */\nexport const PHYSICAL_TOM_PARAMS: readonly VoiceParamSpec[] = [\n")
	for _, spec := range drum.PhysicalTomSpecs() {
		writeSpec(&out, spec)
	}
	out.WriteString("];\n")

	return out.String()
}

func writeSpec(out *strings.Builder, spec drum.ParamSpec) {
	fmt.Fprintf(out, "  {\n")
	fmt.Fprintf(out, "    id: %s,\n", quote(spec.ID))
	fmt.Fprintf(out, "    label: %s,\n", quote(spec.Label))
	fmt.Fprintf(out, "    name: %s,\n", quote(spec.Name))
	fmt.Fprintf(out, "    unit: %s,\n", quote(spec.Unit))
	if len(spec.Choices) > 0 {
		fmt.Fprintf(out, "    choices: [%s],\n", quoteList(spec.Choices))
	}
	fmt.Fprintf(out, "    kind: %s,\n", quote(spec.Kind.String()))
	fmt.Fprintf(out, "    min: %s,\n", num(spec.Min))
	fmt.Fprintf(out, "    max: %s,\n", num(spec.Max))
	fmt.Fprintf(out, "    shipped: %s,\n", num(spec.Shipped))
	fmt.Fprintf(out, "    default: %s,\n", num(spec.Default))
	fmt.Fprintf(out, "    digits: %d,\n", spec.Digits)
	fmt.Fprintf(out, "  },\n")
}

func quoteList(values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = quote(value)
	}

	return strings.Join(quoted, ", ")
}

func maxParams() int {
	widest := 0

	for track := range drum.TrackCount {
		if n := len(drum.SpecsForTrack(track)); n > widest {
			widest = n
		}
	}

	return widest
}
